steps:
  - label: ":hammer: Build"
    key: build
    command: |
      npm install
      npm run build
      tar -czvf bundle.tar.gz build
    artifact_paths: bundle.tar.gz
    plugins:
      - docker#v5.9.0:
          image: "node:21"
          user: node

  - label: ":rocket: Deploy"
    command: echo "Launch!"
    key: deploy
    depends_on: build