steps:
  - label: ":hammer: Build"
    command: |
      apt install -y nodejs
      npm install
      npm run build
    key: build

  - label: ":rocket: Deploy"
    command: echo "Launch!"
    key: deploy
    depends_on: build