steps:
  - label: ":hammer: Build"
    key: build
    command: |
      npm install
      npm run build
      tar -czvf bundle.tar.gz build
    artifact_paths: bundle.tar.gz
    plugins:
      - docker#v5.9.0:
          image: "node:21"
          user: node

  - label: ":docker: Containerize"
    key: containerize
    depends_on: build
    command: |
      buildkite-agent artifact download bundle.tar.gz .
      tar -xvf bundle.tar.gz
      ./containerize.sh
      
      doctl registry login --expiry-seconds 30 --access-token $$DIGITAL_OCEAN_PAT
      buildah tag testpropeller-documentation registry.digitalocean.com/krasnov/testpropeller-documentation:$BUILDKITE_COMMIT
      buildah push registry.digitalocean.com/krasnov/testpropeller-documentation:$BUILDKITE_COMMIT
      
      flyctl auth docker --access-token $$FLY_ACCESS_TOKEN
      buildah tag testpropeller-documentation registry.fly.io/testpropeller-documentation:$BUILDKITE_COMMIT
      buildah push registry.fly.io/testpropeller-documentation:$BUILDKITE_COMMIT

  - label: ":rocket: Deploy"
    key: deploy
    depends_on: containerize
    command: fly deploy --app testpropeller-documentation --image registry.fly.io/testpropeller-documentation:$BUILDKITE_COMMIT
