steps:
  - label: ":hammer: Build"
    key: build
    command: |
      npm install
      npm run build
      tar -czvf bundle.tar.gz build
    artifact_paths: bundle.tar.gz
    plugins:
      - docker#v5.9.0:
          image: "node:21"
          user: node

  - label: ":docker: Containerize"
    key: containerize
    depends_on: build
    command: |
      buildkite-agent artifact download bundle.tar.gz .
      ls -l
      tar -xf bundle.tar.gz
      ls -l
      ls -l build

  - label: ":rocket: Deploy"
    key: deploy
    depends_on: containerize
    command: echo "Launch!"
