steps:
  - label: ":hammer: Build"
    key: build
    command: |
      npm install
      npm run build
    artifact_paths: "./build"
    plugins:
      - docker#v5.9.0:
          image: "node:21"

  - label: ":rocket: Deploy"
    command: echo "Launch!"
    key: deploy
    depends_on: build