steps:
  - label: ":hammer: Build"
    key: build
    command: |
      npm install
      npm run build
      tar -czvf bundle.tar.gz build
    artifact_paths: bundle.tar.gz
    plugins:
      - docker#v5.9.0:
          image: "node:21"
          user: node

  - label: ":docker: Containerize"
    key: containerize
    depends_on: build
    command: |
      buildkite-agent artifact download bundle.tar.gz .
      CONTAINER=$(buildah from docker.io/library/alpine:3.19)
      buildah copy $CONTAINER build /app
      buildah config --author "dennis@testpropeller.com" $CONTAINER
      buildah commit $CONTAINER testpropeller-documentation
      buildah rm $CONTAINER

  - label: ":rocket: Deploy"
    key: deploy
    depends_on: containerize
    command: echo "deploy!"
