steps:
  - label: ":hammer: Build"
    key: build
    command: |
      npm install
      npm run build
      apt update
      apt install -y zip
      zip -r bundle.zip build
    artifact_paths: bundle.zip
    plugins:
      - docker#v5.9.0:
          image: "node:21"
          user: node

  - label: ":rocket: Deploy"
    command: echo "Launch!"
    key: deploy
    depends_on: build